// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhncM7-h1xL5AmoA7cPEjdg1JEpM0JkcU',
    appId: '1:1098252182568:web:027135cde5259dddfe011d',
    messagingSenderId: '1098252182568',
    projectId: 'beerorder-decb4',
    authDomain: 'beerorder-decb4.firebaseapp.com',
    storageBucket: 'beerorder-decb4.appspot.com',
    measurementId: 'G-SYQP43L913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlPEtFFlwn7sy-MWxZwmaSmchqETvQak',
    appId: '1:1098252182568:android:9cf8f8ea2a18d288fe011d',
    messagingSenderId: '1098252182568',
    projectId: 'beerorder-decb4',
    storageBucket: 'beerorder-decb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUn-EcTZP4xzHWnVBQvO6JgTHqsV-NEIY',
    appId: '1:1098252182568:ios:62fd107ec251694bfe011d',
    messagingSenderId: '1098252182568',
    projectId: 'beerorder-decb4',
    storageBucket: 'beerorder-decb4.appspot.com',
    iosClientId: '1098252182568-7aadl272gj09i8kv9m3cvnklurdknraf.apps.googleusercontent.com',
    iosBundleId: 'com.example.casinoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUn-EcTZP4xzHWnVBQvO6JgTHqsV-NEIY',
    appId: '1:1098252182568:ios:62fd107ec251694bfe011d',
    messagingSenderId: '1098252182568',
    projectId: 'beerorder-decb4',
    storageBucket: 'beerorder-decb4.appspot.com',
    iosClientId: '1098252182568-7aadl272gj09i8kv9m3cvnklurdknraf.apps.googleusercontent.com',
    iosBundleId: 'com.example.casinoApp',
  );
}
